export interface FormularyItem {
  id: string;
  shelfLocation: string;
  genericName: string;
  brandName?: string;
  chemicalName?: string;
  dosage: string;
  itemType: 'MEDICATION' | 'OTC' | 'SUPPLY';
  stockUnit: string;
  subUnit: string;
  bottlesAvailable: number;
  pillsPerBottle: number;
  looseUnitsAvailable: number;
  expirationDate: string;
  lotNumbers: string;
  directions: string;
}

// Complete 13 Meyer Center Community Clinic Medication Formulary from original spreadsheet
export const originalSpreadsheetInventory: FormularyItem[] = [
  {
    id: 'meyer-1',
    shelfLocation: 'Dermatology',
    genericName: 'Clobetasol Propionate',
    brandName: 'Clobetasol 0.05%',
    chemicalName: 'Ultra-High Potency Topical Steroid',
    dosage: '0.05% Cream (30g Tube)',
    itemType: 'MEDICATION',
    stockUnit: 'Tubes',
    subUnit: 'g',
    bottlesAvailable: 24,
    pillsPerBottle: 30,
    looseUnitsAvailable: 0,
    expirationDate: '2026-09-30',
    lotNumbers: JSON.stringify(['153224031A']),
    directions: 'Apply a thin layer to the affected area as directed by provider. [Container Volume: 30g Tube]',
  },
  {
    id: 'meyer-2',
    shelfLocation: 'Dermatology',
    genericName: 'Fluocinonide',
    brandName: 'Fluocinonide 0.05%',
    chemicalName: 'High-Potency Topical Corticosteroid',
    dosage: '0.05% Cream (30g Tube)',
    itemType: 'MEDICATION',
    stockUnit: 'Tubes',
    subUnit: 'g',
    bottlesAvailable: 24,
    pillsPerBottle: 30,
    looseUnitsAvailable: 0,
    expirationDate: '2026-10-31',
    lotNumbers: JSON.stringify(['153425002A']),
    directions: 'Apply a thin layer to the affected area as directed by provider. [Container Volume: 30g Tube]',
  },
  {
    id: 'meyer-3',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Cetirizine HCl',
    brandName: 'Zyrtec Allergy',
    chemicalName: 'Second-Generation Antihistamine',
    dosage: '10 mg Tablet',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 29,
    pillsPerBottle: 30,
    looseUnitsAvailable: 0,
    expirationDate: '2028-05-31',
    lotNumbers: JSON.stringify(['3495B1AA']),
    directions: 'Take 1 tablet by mouth once daily as needed for allergies. (Starting stock: 29 bottles × 30 tablets = 870 tablets)',
  },
  {
    id: 'meyer-4',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Cetirizine Liquid Gels',
    brandName: 'Zyrtec Allergy Liquid-Filled',
    chemicalName: 'Second-Generation Antihistamine',
    dosage: '10 mg Liquid-Filled Capsule',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'capsules',
    bottlesAvailable: 16,
    pillsPerBottle: 25,
    looseUnitsAvailable: 0,
    expirationDate: '2027-07-31',
    lotNumbers: JSON.stringify(['3495B1AA']),
    directions: 'Take 1 liquid-filled capsule by mouth once daily as needed for allergies.',
  },
  {
    id: 'meyer-5',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Diphenhydramine HCl',
    brandName: 'Benadryl Allergy',
    chemicalName: 'First-Generation Antihistamine',
    dosage: '25 mg Tablet',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 72,
    pillsPerBottle: 48,
    looseUnitsAvailable: 0,
    expirationDate: '2027-02-28',
    lotNumbers: JSON.stringify(['EEA191']),
    directions: 'Take 1 tablet by mouth every 4–6 hours as needed for allergy symptoms.',
  },
  {
    id: 'meyer-6',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Facial Cleanser',
    brandName: 'Neutrogena Hydro Boost Hydrating Gel Cleanser',
    chemicalName: 'Gel Cleanser Fragrance Free',
    dosage: '0.5 fl oz (15 mL) Gel Cleanser',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'mL',
    bottlesAvailable: 10,
    pillsPerBottle: 15,
    looseUnitsAvailable: 0,
    expirationDate: '2027-02-28',
    lotNumbers: JSON.stringify(['1965B2CC']),
    directions: 'Use according to package labeling or provider instructions. [Container Volume: 15 mL Bottle]',
  },
  {
    id: 'meyer-7',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Hyaluronic Acid Moisturizer with Sunscreen',
    brandName: 'Neutrogena Hydro Boost Sunscreen SPF 50',
    chemicalName: 'Sunscreen / Facial Moisturizer',
    dosage: 'SPF 50 / 1.7 fl oz (50 mL) Lotion',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'mL',
    bottlesAvailable: 10,
    pillsPerBottle: 50,
    looseUnitsAvailable: 0,
    expirationDate: '2027-02-28',
    lotNumbers: JSON.stringify(['1965B2CC']),
    directions: 'Use according to package labeling or provider instructions. [Container Volume: 50 mL Bottle]',
  },
  {
    id: 'meyer-8',
    shelfLocation: 'Over-The-Counter (OTC)',
    genericName: 'Sunscreen / Collagen Bank SPF Moisturizer',
    brandName: 'Neutrogena Collagen Bank SPF 30',
    chemicalName: 'Sunscreen / Collagen Moisturizer',
    dosage: 'SPF 30 / 2.7 fl oz (80 mL) Lotion',
    itemType: 'OTC',
    stockUnit: 'Bottles',
    subUnit: 'mL',
    bottlesAvailable: 48,
    pillsPerBottle: 80,
    looseUnitsAvailable: 0,
    expirationDate: '2027-01-13',
    lotNumbers: JSON.stringify(['04425CA']),
    directions: 'Use according to package labeling or provider instructions. [Container Volume: 80 mL Bottle]',
  },
  {
    id: 'meyer-9',
    shelfLocation: 'Psychiatry',
    genericName: 'Aripiprazole',
    brandName: 'Abilify',
    chemicalName: 'Atypical Antipsychotic',
    dosage: '10 mg Tablet',
    itemType: 'MEDICATION',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 4,
    pillsPerBottle: 30,
    looseUnitsAvailable: 0,
    expirationDate: '2027-01-09',
    lotNumbers: JSON.stringify(['0000088525']),
    directions: 'Take as directed by provider.',
  },
  {
    id: 'meyer-10',
    shelfLocation: 'Psychiatry',
    genericName: 'Bupropion HCl SR',
    brandName: 'Wellbutrin SR',
    chemicalName: 'Aminoketone Antidepressant',
    dosage: '100 mg Sustained-Release 12-Hour Tablet',
    itemType: 'MEDICATION',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 12,
    pillsPerBottle: 500,
    looseUnitsAvailable: 0,
    expirationDate: '2027-05-03',
    lotNumbers: JSON.stringify(['0000134515']),
    directions: 'Take as directed by provider. Swallow whole; do not crush, chew, or split.',
  },
  {
    id: 'meyer-11',
    shelfLocation: 'Psychiatry',
    genericName: 'Escitalopram',
    brandName: 'Lexapro',
    chemicalName: 'SSRI Antidepressant',
    dosage: '5 mg Tablet',
    itemType: 'MEDICATION',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 24,
    pillsPerBottle: 100,
    looseUnitsAvailable: 0,
    expirationDate: '2027-02-28',
    lotNumbers: JSON.stringify(['0000093834']),
    directions: 'Take as directed by provider.',
  },
  {
    id: 'meyer-12',
    shelfLocation: 'Psychiatry',
    genericName: 'Lurasidone HCl',
    brandName: 'Latuda',
    chemicalName: 'Atypical Antipsychotic',
    dosage: '20 mg Oral Tablet',
    itemType: 'MEDICATION',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 24,
    pillsPerBottle: 30,
    looseUnitsAvailable: 0,
    expirationDate: '2026-09-30',
    lotNumbers: JSON.stringify(['A241211']),
    directions: 'Take as directed by provider. Take with food.',
  },
  {
    id: 'meyer-13',
    shelfLocation: 'Psychiatry',
    genericName: 'Quetiapine Fumarate',
    brandName: 'Seroquel',
    chemicalName: 'Atypical Antipsychotic',
    dosage: '300 mg Tablet',
    itemType: 'MEDICATION',
    stockUnit: 'Bottles',
    subUnit: 'tablets',
    bottlesAvailable: 24,
    pillsPerBottle: 100,
    looseUnitsAvailable: 0,
    expirationDate: '2026-09-30',
    lotNumbers: JSON.stringify(['E244744']),
    directions: 'Take as directed by provider.',
  },
];
